// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/wxlbd/admin-go/internal/api/handler/admin"
	"github.com/wxlbd/admin-go/internal/api/handler/admin/infra"
	system2 "github.com/wxlbd/admin-go/internal/api/handler/admin/system"
	"github.com/wxlbd/admin-go/internal/api/router"
	"github.com/wxlbd/admin-go/internal/middleware"
	"github.com/wxlbd/admin-go/internal/pkg/permission"
	"github.com/wxlbd/admin-go/internal/pkg/websocket"
	"github.com/wxlbd/admin-go/internal/repo"
	infra2 "github.com/wxlbd/admin-go/internal/service/infra"
	"github.com/wxlbd/admin-go/internal/service/system"
	"github.com/wxlbd/admin-go/pkg/cache"
	"github.com/wxlbd/admin-go/pkg/database"
	"github.com/wxlbd/admin-go/pkg/logger"
)

// Injectors from wire.go:

func InitApp() (*gin.Engine, error) {
	db := database.InitDB()
	client := cache.InitRedis()
	query := repo.NewQuery(db)
	configService := system.NewConfigService(query)
	configHandler := infra.NewConfigHandler(configService)
	fileConfigService := infra2.NewFileConfigService(query)
	fileConfigHandler := infra.NewFileConfigHandler(fileConfigService)
	fileService := infra2.NewFileService(query, fileConfigService)
	fileHandler := infra.NewFileHandler(fileService)
	apiAccessLogService := infra2.NewApiAccessLogService(query)
	apiAccessLogHandler := infra.NewApiAccessLogHandler(apiAccessLogService)
	apiErrorLogService := infra2.NewApiErrorLogService(query)
	apiErrorLogHandler := infra.NewApiErrorLogHandler(apiErrorLogService)
	zapLogger := logger.NewLogger()
	v := ProvideJobHandlers()
	scheduler, err := infra2.NewScheduler(query, zapLogger, v)
	if err != nil {
		return nil, err
	}
	jobService := infra2.NewJobService(query, scheduler)
	jobHandler := infra.NewJobHandler(jobService)
	jobLogService := infra2.NewJobLogService(query)
	jobLogHandler := infra.NewJobLogHandler(jobLogService)
	manager := websocket.NewManager()
	webSocketHandler := infra.NewWebSocketHandler(manager, zapLogger)
	handlers := infra.NewHandlers(configHandler, fileConfigHandler, fileHandler, apiAccessLogHandler, apiErrorLogHandler, jobHandler, jobLogHandler, webSocketHandler)
	areaHandler := system2.NewAreaHandler()
	roleService := system.NewRoleService(query)
	permissionService := system.NewPermissionService(query, roleService)
	menuService := system.NewMenuService(query)
	oAuth2TokenService := system.NewOAuth2TokenService()
	smsTemplateService := system.NewSmsTemplateService(query)
	smsLogService := system.NewSmsLogService(query)
	smsClientFactory := system.NewSmsClientFactory()
	smsSendService := system.NewSmsSendService(query, smsTemplateService, smsLogService, smsClientFactory)
	smsCodeService := system.NewSmsCodeService(query, client, smsSendService)
	loginLogService := system.NewLoginLogService(query)
	deptService := system.NewDeptService(query)
	userService := system.NewUserService(query, deptService)
	socialUserService := system.NewSocialUserService(query)
	authService := system.NewAuthService(query, permissionService, roleService, menuService, oAuth2TokenService, smsCodeService, loginLogService, userService, socialUserService)
	authHandler := system2.NewAuthHandler(authService)
	deptHandler := system2.NewDeptHandler(deptService)
	dictService := system.NewDictService(query)
	dictHandler := system2.NewDictHandler(dictService)
	loginLogHandler := system2.NewLoginLogHandler(loginLogService)
	menuHandler := system2.NewMenuHandler(menuService)
	noticeService := system.NewNoticeService(query)
	noticeHandler := system2.NewNoticeHandler(noticeService, webSocketHandler)
	notifyService := system.NewNotifyService(query)
	notifyHandler := system2.NewNotifyHandler(notifyService)
	operateLogService := system.NewOperateLogService(query)
	operateLogHandler := system2.NewOperateLogHandler(operateLogService)
	tenantService := system.NewTenantService(query, roleService, permissionService)
	permissionHandler := system2.NewPermissionHandler(permissionService, tenantService)
	postService := system.NewPostService(query)
	postHandler := system2.NewPostHandler(postService)
	roleHandler := system2.NewRoleHandler(roleService)
	tenantHandler := system2.NewTenantHandler(tenantService)
	tenantPackageService := system.NewTenantPackageService(query, tenantService)
	tenantPackageHandler := system2.NewTenantPackageHandler(tenantPackageService)
	userHandler := system2.NewUserHandler(userService)
	smsChannelService := system.NewSmsChannelService(query)
	smsChannelHandler := system2.NewSmsChannelHandler(smsChannelService)
	smsTemplateHandler := system2.NewSmsTemplateHandler(smsTemplateService, smsSendService)
	smsLogHandler := system2.NewSmsLogHandler(smsLogService)
	mailService := system.NewMailService(db)
	mailHandler := system2.NewMailHandler(mailService)
	systemHandlers := system2.NewHandlers(areaHandler, authHandler, deptHandler, dictHandler, loginLogHandler, menuHandler, noticeHandler, notifyHandler, operateLogHandler, permissionHandler, postHandler, roleHandler, tenantHandler, tenantPackageHandler, userHandler, smsChannelHandler, smsTemplateHandler, smsLogHandler, mailHandler)
	adminHandlers := &admin.AdminHandlers{
		Infra:  handlers,
		System: systemHandlers,
	}
	enforcer, err := permission.InitEnforcer(db)
	if err != nil {
		return nil, err
	}
	casbinMiddleware := middleware.NewCasbinMiddleware(enforcer, permissionService)
	engine := router.InitRouter(db, client, adminHandlers, casbinMiddleware)
	return engine, nil
}

// wire.go:

// ProvideJobHandlers 聚合定时任务处理器，当前为空（管理后台基础模板）
func ProvideJobHandlers() []infra2.JobHandler {
	return []infra2.JobHandler{}
}
